# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@" "noatime" "compress=zstd" "ssd" "space_cache=v2" ];
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/4a3d57fa-af54-47aa-a2a1-56be7cbd8786";

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@home" "noatime" "compress=zstd" "ssd" "space_cache=v2" ];
  };

  fileSystems."/var" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@var" "noatime" "compress=zstd" "ssd" "space_cache=v2" ];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@snapshots" "noatime" "compress=zstd" "ssd" "space_cache=v2" ];
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B8B0-649D";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/efcd267c-ad95-43f5-839b-bb8cfd44e999";
    fsType = "btrfs";
    options = [ "noatime" "compress=zstd" "ssd" "space_cache=v2" ];
  };

  swapDevices = [
    { device = "/swapfile"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
